<a href="https://colab.research.google.com/github/gaargly/gaargly.github.io/blob/master/2021_06_18_Lira_Samanta_Assignment1_Dr_Kasaran_class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment-1

1. Write a NumPy program to convert a list and tuple into arrays. 

List to array:

[1 2 3 4 5 6 7 8]

Tuple to array:

[[8 4 6]
[1 2 3]]

In [1]:
import numpy as np

# List to Array
list1 = [1, 2, 3, 4, 5, 6, 7, 8]
np.array(list1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [2]:
# Tuple to Array
tuple1 = (1, 2, 3, 4, 5, 6, 7, 8)
np.array(tuple1)

array([1, 2, 3, 4, 5, 6, 7, 8])

2. Write a NumPy program to append values to the end of an array.

Expected Output:

Original array:
[10, 20, 30]

After append values to the end of the array:
[10 20 30 40 50 60 70 80 90]

In [46]:
arr = [10, 20, 30]
arr = np.append(arr, [40, 50, 60, 70, 80, 90])
print(arr)

[10 20 30 40 50 60 70 80 90]


3. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

Sample Array [0, 12, 45.21 ,34, 99.91]

Values in Fahrenheit degrees:                                           
[  0.    12.    45.21  34.    99.91]                                    
Values in  Centigrade degrees:                                          
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]

In [13]:
degrees_C = np.array([0, 12, 45.21, 34, 99.91])
degrees_F = (5*degrees_F/9 - 5*32/9)
print(degrees_F)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


4. Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements

In [47]:
arr = np.array([5, 10, 15])
print("Size:", arr.size)
print("Length:", arr.itemsize)
print("Bytes:", arr.nbytes)

Size: 3
Length: 8
Bytes: 24


5. Write a NumPy program to find common values between two arrays.

Array1:  [ 0 10 20 40 60]                                              
Array2:  [10, 30, 40]                                                  
Common values between two arrays:                                      
[10 40]

In [48]:
array1 = np.array([0, 10, 20, 40, 60])
array2 = np.array([10, 30, 40])
np.intersect1d(array1, array2)

array([10, 40])

6. Write a NumPy program to get the unique elements of an array. 

Expected Output:
Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
[2 3]]
Unique elements of the above array:
[1 2 3]

In [25]:
orig_array = np.array([10, 10, 20, 20, 30, 30])
orig_array2 = np.array([[1, 1],[2,3]])

print(np.unique(orig_array))
print(np.unique(orig_array2))

[10 20 30]
[1 2 3]


7. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

Array1:  [ 0 10 20 40 60 80]                                           
Array2:  [10, 30, 40, 50, 70]                                          
Unique values in array1 that are not in array2:                        
[ 0 20 60 80]

In [27]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])
np.setdiff1d(array1, array2)

array([ 0, 20, 60, 80])

8. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.

Array1:  [ 0 10 20 40 60 80]                                           
Array2:  [10, 30, 40, 50, 70]                                          
Unique values that are in only one (not both) of the input arrays:     
[ 0 20 30 50 60 70 80]

In [28]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])
np.setxor1d(array1, array2)

array([ 0, 20, 30, 50, 60, 70, 80])

9. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

Array1:  [ 0 10 20 40 60 80]                                           
Array2:  [10, 30, 40, 50, 70]                                          
Unique sorted array of values that are in either of the two input array
s:                                                                     
[ 0 10 20 30 40 50 60 70 80]

In [29]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = np.array([10, 30, 40, 50, 70])
np.union1d(array1, array2)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

10. Write a NumPy program to test whether all elements in an array evaluate to True.
Note: 0 evaluates to False in python.

In [33]:
print(np.all([[True, True, True]]))
print(np.all([[True, True, False]]))
print(np.all([[True, True, 0]]))

True
False
False
None


11. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

Original array:  [1 2 3 4 5 6]                                         
Maximum Values:  5                                                     
Minimum Values:  0

In [49]:
orig_array = np.array([1, 2, 3, 4, 5, 6])
print(np.argmax(orig_array))
print(np.argmin(orig_array))

5
0


12. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

In [50]:
arr = np.array([10, 15, 220])
print(arr[arr > 10])

[ 15 220]


13. Write a NumPy program to create an array of ones of size 2 and an array of zeros of size 2.

In [39]:
ones = np.ones(2)
zeros = np.zeros(2)
print(ones)
print(zeros)

[1. 1.]
[0. 0.]


14. Write a NumPy program to create a contiguous flattened array.

Original array:                                                        
[[10 20 30]                                                            
 [20 40 50]]                                                           
New flattened array:                                                   
[10 20 30 20 40 50] 

In [51]:
orig_array = np.array([[10, 20, 30], [20, 40, 50]])
flat_arr = np.ravel(orig_array)
print(flat_arr)

[10 20 30 20 40 50]


15. Write a NumPy program to create a new shape to an array without changing its data.

Reshape 3x2:                                                           
[[1 2]                                                                 
 [3 4]                                                                 
 [5 6]]                                                                
Reshape 2x3:                                                           
[[1 2 3]                                                               
 [4 5 6]] 

In [52]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_one = np.reshape(arr, (3,2))
reshaped_two = np.reshape(arr, (2,3))
print(reshaped_one)
print(reshaped_two)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


16. Write a NumPy program to change the data type of an array.

[[ 2  4  6]                                                            
 [ 6  8 10]]                                                           
Data type of the array x is: int32                                     
New Type:  float64                                                     
[[  2.   4.   6.]                                                      
 [  6.   8.  10.]]

In [53]:
arr = np.array([[2, 4, 6], [6, 8, 10]])
changed = arr.astype(float)
print(arr)

[[ 2  4  6]
 [ 6  8 10]]


17. Write a NumPy program to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.

In [43]:
array_1d =  np.logspace(2., 5., 20)
print(array_1d)

[   100.            143.84498883    206.91380811    297.63514416
    428.13323987    615.84821107    885.86679041   1274.2749857
   1832.98071083   2636.65089873   3792.69019073   5455.59478117
   7847.59970351  11288.37891685  16237.76739189  23357.2146909
  33598.18286284  48329.30238572  69519.27961776 100000.        ]


18. Write a NumPy program to concatenate two 2-dimensional arrays.
Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]

[[ 0  1  3  0  2  4]                                                   
 [ 5  7  9  6  8 10]] 

In [44]:
x = np.array([[0, 1, 3], [5, 7, 9]])
y = np.array([[0, 2, 4], [6, 8, 10]])
z = np.concatenate((x, y), 1)
print(z)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


19. Write a Python program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order.
Sample array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]            
After splitting:                                                       
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13,
 14])] 

In [55]:
arr = np.arange(1, 15)
print("Original array: ", arr)
print("After splitting: ")
print(np.split(arr, [2, 6]))

Original array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting: 
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


20. Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis.
Sample array :
[[ 0 1 2 3]
[ 4 5 6 7]
[ 8 9 10 11]
[12 13 14 15]]


After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)] 

In [56]:
arr = np.arange(16).reshape((4, 4))
print("Original array: ", arr)
print("After splitting horizontally:")
print(np.hsplit(arr, [2, 6]))

Original array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)]


21. Write a NumPy program to get the number of nonzero elements in an array.
Original array:                                                        
[[ 0 10 20]                                                            
 [20 30 40]]                                                           
Number of non zero elements in the above array:                        
5 

In [57]:
arr = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(arr)
print("Number of non zero elements in the above array:")
print(np.count_nonzero(arr))

Original array:
[[ 0 10 20]
 [20 30 40]]
Number of non zero elements in the above array:
5
